spring:
  datasource:
    url: jdbc:h2:mem:tareasdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: mySuperSecretKeyForJWT1234567890!
  expiration: 3600000 # 1 hora en milisegundos (1 hora)

crendential-api-key:
  email: admin@nuevo.com
  password: admin123 # Puedes cambiarlo si lo deseas

